Dar/Dar/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from customer.views import logout

urlpatterns = [
    path('admin/', admin.site.urls, name='secondHand'),
    path('', include('secondHand.urls')),
]

Dar/customer/urls.py
import os

from django.urls import path
from .views import *
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from Auction.views import make_auction, make_bid
from payment.views import charge_account
from notification.views import *

urlpatterns = [
                  url(r'^costumerBase/$', costumerHome, name='costumerHome'),
                  url(r'^add_advertisement/$', publish_adv, name='publish_ad_form'),
                  url(r'^my_advertisement/$', my_adv, name='my_adv'),
                  url(r'^edit_profile/$', edit_profile, name='edit_profile'),
                  url(r'^logout/$', logout, name='logout'),
                  url(r'^(?P<ad_id>[0-9]+)/$', view_ad, name='view_ad'),
                  url(r'^home/$', recent_adv, name='home'),
                  url(r'^(?P<ad_id>[0-9]+)/add_comment/$', add_comment, name='add_comment'),
                  url(r'^(?P<ad_id>[0-9]+)/add_auction/$', make_auction, name='add_auction'),
                  url(r'^(?P<ac_id>[0-9]+)/make_bid/$', make_bid, name='make_bid'),
                  url(r'^charge_account/$', charge_account, name='charge_account'),
                  url(r'^invite/$', invite, name='invite'),
                  url(r'^search/$', ad_search, name='customer_search'),
                  url(r'^transaction_history/$', transaction_history, name='transaction_history'),
                  url(r'^credits/$', credits, name='credits'),
                  url(r'^new_notification/$', new_notification, name='new_notification'),
                  url(r'^all_notification/$', all_notification, name='all_notification'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dar/secondHand/urls.py
from django.urls import path, re_path
from django.conf.urls import url, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from register.views import *
from ContactUs.views import *
from customer.views import *
from django.contrib.auth import views as auth_views
from payment.views import *

urlpatterns = [
                  url(r'^customer/', include(('customer.urls', 'customer'), namespace="customer")),
                  path('', home, name='home'),
                  path('index', index, name='index'),
                  path('login', login, name='login'),
                  path('logout/', logout, name='logout'),
                  path('all_ads', all_ads, name='all_ads'),
                  path('recent_adv', recent_adv_menu, name='recent_adv'),
                  path('search_by_category', search_by_category, name='search_by_category'),
                  path('search_by_address', search_by_address, name='search_by_address'),
                  path('contact_us', contact, name='contact'),
                  path('complaint', complaint, name='complaint'),
                  path('search', search, name='search'),
                  path('register', register, name='register'),
                  url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      activate, name='activate'),
                  url(r'^(?P<ad_id>[0-9]+)/$', view_ad_raw, name='view_ad_raw'),
                  url(r'^(?P<ad_id>[0-9]+)/add_comment/$', add_comment, name='add_comment'),
                  path('password_reset/', auth_views.PasswordResetView.as_view(),
                       {'template_name': 'registration/password_reset_form.html'}, name='password_reset'),
                  path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
                       {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
                  re_path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
                          auth_views.PasswordResetConfirmView.as_view(),
                          {'template_name': 'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
                  path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
                       {'template_name': 'registration/password_reset_confirm.html'}, name='password_reset_complete'),
                  url(r'^transaction_result/(?P<trans_id>[\w|\W]+)/(?P<result>[\w|\W]+)/$',
                      transaction_result, name='transaction_result'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dar/customer/models.py
from django.db import models

# Create your models here.

Dar/notification/models.py
from django.db import models
from django.utils import timezone
from secondHand.models import *

class Notification(models.Model):
    customer = models.ForeignKey(Customer, related_name='customer', on_delete=models.CASCADE)
    message = models.CharField(max_length=500, default="Nothing", blank=False, null=False)
    time = models.DateTimeField(default=timezone.now())
    read = models.BooleanField(default=False)

    def get_message(self):
        if self.message == "Nothing":
            return "پیام خالی می‌باشد"
        return self.message

Dar/secondHand/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default='customer', max_length=20)
    nationalID = models.CharField(max_length=10, unique=True)
    location_address = models.CharField(default='', max_length=400)
    birthday = models.DateTimeField(default='2000-01-01', null=True)



class Address(models.Model):
    lat = models.DecimalField(max_digits=9, decimal_places=6, default=35.70530498029150)
    lng = models.DecimalField(max_digits=9, decimal_places=6, default=51.34547698029149)
    profile=models.ForeignKey(Profile, on_delete=models.CASCADE)


class Customer(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    phone_number = models.IntegerField()
    credit = models.IntegerField(default="0")
    invitation_code = models.CharField(default="0", max_length=30)

    def get_published_advertises_by_me(self):
        return Advertise.objects.get(seller=self)

    def get_bought_advertises(self):
        return Advertise.objects.get(buyer=self)

    def add_comment(self, desc, advertise):
        comment = Comment(time=timezone.now(), desc=desc, sender=self, advertise=advertise)
        comment.save()

    def add_advertise(self, title, desc, price, off, category1, category2, category3, address):
        cat1 = Category_type_1.objects.get(name=category1)
        cat2 = Category_type_2.objects.get(name=category2, cat_lev1=cat1)
        cat3 = Category_type_3.objects.get(name=category3, cat_lev2=cat2)
        advertise = Advertise(title=title, desc=desc, price=price, off= off, seller=self, category=cat3, address=address)
        advertise.save()

    def add_credit(self, val):
        self.credit += val
        self.save()

    def reserve_credit(self, value, advertise):
        reserve_cr = Reserve_credit(value=value, customer=self, advertise=advertise)
        reserve_cr.save()
        self.credit -= value
        self.save()

    def free_credit(self, reserve_cr):
        reserve_cr.status = "free"
        reserve_cr.save()
        self.credit += reserve_cr.value
        self.save()


class Category_type_1(models.Model):
    name = models.CharField(max_length=20, unique=True, primary_key=True)


class Category_type_2(models.Model):
    cat_lev1 = models.ForeignKey(Category_type_1, related_name='cat_lev1', on_delete=models.CASCADE)
    name = models.CharField(max_length=20)


class Category_type_3(models.Model):
    cat_lev2 = models.ForeignKey(Category_type_2, related_name='cat_lev2', on_delete=models.CASCADE)
    name = models.CharField(max_length=20)


class Advertise(models.Model):
    title = models.CharField(max_length=30, null=False)
    desc = models.CharField(max_length=400, null=True)
    published_date = models.DateTimeField(default=timezone.now(), null=False, blank=False)
    price = models.IntegerField(default="0")
    status = models.CharField(default='Not sold yet', max_length=20)
    accepted = models.BooleanField(default=False)
    seller = models.ForeignKey(Customer, related_name='seller', on_delete=models.CASCADE)
    buyer = models.ForeignKey(Customer, related_name='buyer', null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category_type_3, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    priority = models.IntegerField(default='1')
    has_auction = models.BooleanField(default=False)
    off = models.IntegerField(default=0)

    def sell_item(self, buyer):
        self.buyer = buyer
        self.status = 'has Sold'
        self.save()

    def add_image(self, image):
        image_advertise = Image_Advertise(advertise=self, image=image)
        image_advertise.save()

    def get_images(self):
        return Image_Advertise(advertise=self)


class Comment(models.Model):
    time = models.DateTimeField()
    advertise = models.ForeignKey(Advertise, on_delete=models.CASCADE, blank=False, null=False)
    desc = models.CharField(max_length=300, blank=False, null=False)
    sender = models.ForeignKey(Customer, blank=False, null=False, on_delete=models.CASCADE)



class Worker_Advertise(models.Model):
    worker = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=False, null=False)
    advertise = models.ForeignKey(Advertise, on_delete=models.CASCADE, blank=False, null=False)


class Image_Advertise(models.Model):
    image = models.ImageField(upload_to='ad_images', blank=True)
    advertise = models.ForeignKey(Advertise, on_delete=models.CASCADE, blank=False, null=False)



class Reserve_credit(models.Model):
    value = models.IntegerField()
    customer = models.ForeignKey(Customer, blank=False, null=False, on_delete=models.CASCADE)
    advertise = models.ForeignKey(Advertise, blank=False, null=False, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, default="reserved")

Dar/Auction/forms.py
from django import forms
from .models import *

class AuctionForm(forms.ModelForm):
    class Meta:
        model= Auction
        exclude=['item','seller','starting_date', 'status']


class BidForm(forms.ModelForm):
    class Meta:
        model= Bid
        exclude=['bidder','date','auction']

Dar/customer/forms.py
from django import forms
from secondHand.models import *
from Auction.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AdvertiseForm(forms.ModelForm):
    class Meta:
        model = Advertise
        exclude = ['published_date', 'status', 'accepted', 'seller', 'buyer' , 'priority']


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')

    class Meta:
        model = Image_Advertise
        fields = ('image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['time', 'advertise', 'sender']





class SearchForm(forms.Form):
    title=forms.CharField(max_length='100')
    desc=forms.CharField(max_length='1000')
    max_price=forms.IntegerField()
    min_price=forms.IntegerField()


class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    nationalID = forms.IntegerField()
    location_address = forms.CharField(max_length='400')
    phone_number = forms.IntegerField()

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', "password1", "password2", 'nationalID', 'location_address', 'phone_number')

Dar/Auction/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.shortcuts import render
from django.shortcuts import redirect
from secondHand.models import *
from .models import *
from .forms import AuctionForm, BidForm
from django.utils.datetime_safe import datetime
from payment.tasks import *
from notification.models import Notification


def make_auction(request, ad_id):
    advertise = Advertise.objects.get(pk=ad_id)
    if request.method == 'GET':
        return render(request, 'auction.html', {'advertise': advertise})
    if request.method == 'POST':
        form = AuctionForm(request.POST)
        if form.is_valid():
            auction = form.save(commit=False)
            profile = Profile.objects.get(user=request.user)
            seller = Customer.objects.get(profile=profile)
            auction.seller = seller
            auction.item = advertise
            auction.save()
            finish_auction.apply_async((auction.pk,), eta=auction.deadline)
            return redirect('customer:make_bid', ac_id=auction.pk)
    return render(request, 'auction.html', {'advertise': advertise})


def free_last_bidder(bid):
    try:
        bidder = bid.bidder
        auction = bid.auction
        advertise = auction.item
        reserve_cr = Reserve_credit.objects.get(advertise=advertise, customer=bidder, status="reserved")
        bidder.free_credit(reserve_cr)


    except Exception as e:
        print("ERROR IN FREE_LAST_BIDDER")
        print(e)
        pass


def initiate_bid(form, request, value, auction):
    bidder = Profile.objects.get(user=request.user)
    bidder = Customer.objects.get(profile=bidder)
    credit = bidder.credit
    if (value / 10) >= credit:
        return False
    max_bid = auction.get_max_bid()
    if max_bid != None:
        free_last_bidder(max_bid)
    bid = form.save(commit=False)
    bid.bidder = bidder
    bidder.refresh_from_db()
    bid.date = datetime.now().date()
    bid.auction = auction
    bid.save()
    bidder.reserve_credit(value / 10, auction.item)
    message = "مبلغ {0} واحد به دلیل ارائه پیشنهاد در مزایده کالا با عنوان << {1} >> از حساب شما در رزرو قرار گرفت.".format(value/10,auction.item.title)
    notif = Notification(customer=bidder,message=message)
    notif.save()
    return True


def make_bid(request, ac_id):
    auction = Auction.objects.get(pk=ac_id)
    if datetime.now().date() < auction.deadline:
        if request.method == 'GET':
            return render(request, 'bid.html',
                          {'auction': auction, 'bids': auction.get_bids(), 'max_bid': auction.max_bid_value})
        if request.method == 'POST':
            form = BidForm(request.POST)
            if form.is_valid():
                value = form.cleaned_data['value']
                if value > auction.max_bid_value():
                    has_credit = initiate_bid(form, request, value, auction)
                    if not has_credit:
                        log = "موجودی شما کافی نیست. باید حداقل ۱۰ درصد مبلغ پیشنهادی خود را در موجودی کنونی داشته باشید."
                        return render(request, 'unsuccessful_bid.html', {'log': log})
                    return render(request, 'bid.html',
                                  {'auction': auction, 'bids': auction.get_bids(), 'max_bid': auction.max_bid_value})
                else:
                    log = "مبلغ پیشنهادی شما بیشتر از بهترین پیشنهاد موجود برای این مزایده نیست لکن قادر به ثبت پیشنهادتان نیستید."
                    return render(request, 'unsuccessful_bid.html', {'log': log})

        return render(request, 'bid.html',
                      {'auction': auction, 'bids': auction.get_bids(), 'max_bid': auction.max_bid_value})
    else:
        return render(request, 'end-bid.html',
                      {'auction': auction, 'bids': auction.get_bids(), 'max_bid': auction.max_bid_value})

Dar/notification/views.py
from django.shortcuts import render
from .models import Notification
from secondHand.models import *
# Create your views here.

def new_notification(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    customer = Customer.objects.get(profile=profile)
    new_notifs = Notification.objects.filter(customer=customer, read=False).order_by('-time')
    for notif in new_notifs:
        notif.read = True
        notif.save()
    return render(request,"notification.html", {"notifs":new_notifs,"title":"پیام‌های جدید خوانده‌نشده"})



def all_notification(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    customer = Customer.objects.get(profile=profile)
    notifs = Notification.objects.filter(customer=customer).order_by('-time')
    return render(request, "notification.html", {"notifs": notifs , "title":"لیست‌ تمامی پیام‌های شما"})

Dar/customer/templates/ad_search.html
{% extends 'costumerBase.html' %}

{% block title %}
    جست و جو در آگهی ها
{% endblock %}



{% block content %}
    <br>
      <div id="page-content-wrapper" class="offset8">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-md-8" style="float: none; margin: 0 auto;">
                    <div style="background-color: white; margin: 5%; padding: 5%; border-radius: 10px;">
                        <section id="auction">
                            <form class="well form-horizontal" style="direction: rtl;" action="" method="post"
                                  id="auction_form">{% csrf_token %}
                                <fieldset>
                                    <legend>
                                        <center><h2><b>جست و جوی آگهی ها</b></h2></center>
                                    </legend>
                                    <br>

                                    <div class="form-group">
                                        <div class="col-md-12 inputGroupContainer">
                                            <div class="input-group">
                                                    <span class="input-group-addon"><i
                                                            class="glyphicon glyphicon-user"></i></span>
                                                <input name="title" placeholder="عنوان" class="form-control"
                                                       type="text">
                                            </div>
                                        </div>
                                    </div>
                                    <br>

                                    <div class="form-group">
                                        <div class="col-md-12 inputGroupContainer">
                                            <div class="input-group">
                                                    <span class="input-group-addon"><i
                                                            class="glyphicon glyphicon-user"></i></span>
                                                <input name="desc" placeholder="توضیحات"
                                                       class="form-control" type="text">
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <div class="col-md-12 inputGroupContainer">
                                            <div class="input-group">
                                                    <span class="input-group-addon"><i
                                                            class="glyphicon glyphicon-user"></i></span>
                                                <input name="min_price" id="min_price" placeholder="کمینه قیمت"
                                                       class="form-control" type="number">
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <div class="col-md-12 inputGroupContainer">
                                            <div class="input-group">
                                                    <span class="input-group-addon"><i
                                                            class="glyphicon glyphicon-user"></i></span>
                                                <input name="max_price" id="max_price" placeholder="بیشینه قیمت"
                                                       class="form-control" type="number">
                                            </div>
                                        </div>
                                    </div>



                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-6 col-sm-offset-3">
                                                <input type="submit" name="submit" id="search-submit"
                                                       tabindex="4" class="form-control btn btn-register"
                                                       value="جست و جو"
                                                       placeholder="جست و جو">
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Dar/customer/templates/costumerHome.html
{% extends 'costumerBase.html' %}

{% block title %}
    سامانه در
{% endblock %}



{% block content %}
    <!--page content-->
    <div id="page-content-wrapper" class="offset8">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div style="background-color: white; margin: 5%; padding: 5%; border-radius: 10px;">
                        <h1 class="text-right" id="bonyad">سامانه خرید و فروش در</h1>
                        <p class="text-right" id="mashi">در از سال ۱۳۹۲ با هدف خرید و فروش بدون واسطه‌ی آنلاین آغاز به کار کرد. امتیاز برند در توسط شرکت «آگه پردازان هوشمند» (سهامی خاص) در  تمامی مراجع قانونی ثبت شده است.

نیازمندی‌های ریز و درشت شما روی در
                            در در به آسانی می‌توانید نیازمندی‌هایتان را بر اساس محله دسته‌بندی کنید و نزدیک‌ترین‌ها را بیابید.</p>
         <br>
                            <h2 class="text-right"> :خرید و فروش بی‌واسطه</h2>
                         <p class="text-right" id="mashi">
در در کاربران مستقیماً با هم تماس می‌گیرند و هیچ واسطه‌ای در این میان وجود ندارد، پس دقت فرمایید که در خرید و فروشِ شما در هیچ دخالتی ندارد و کاربران باید خودشان جنبه‌های مختلف امنیتی را در نظر بگیرند.</p>

                        <br>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Dar/customer/templates/credit_status.html
{% extends 'costumerBase.html' %}

{% block title %}موجودی حساب{% endblock %}


{% block content %}

    <div class="main">

        <div>
        <div class="row">
            <div class="col-md-4" style="font-size: xx-large;" dir="rtl">موجودی خالص:   {{ credit }}</div>
            <div class="col-md-4" style="font-size: xx-large">رزرو شده: {{ reserved }}</div>
        </div>
        {% if reserve_objects %}

           <center style="font-size: xx-large; margin-top: 2%" dir="rtl">لیست مبالغ رزرو شده</center>
            <table>
                <tr style="font-size: x-large">
                    <th>عنوان کالا</th>
                    <th>مبلغ</th>
                    <th>شماره</th>
                </tr>
                {% for rs in reserve_objects %}
                    <tr class="row" style="font-size: 22px">
                        <td class="col-md-6">{{ rs.advertise.title }}</td>
                        <td class="col-md-5">{{ rs.value }}</td>
                        <td class="col-md-1">
                            {{ forloop.counter }}
                        </td>
                    </tr>
                {% endfor %}


            </table>
        {% endif %}
        </div>

    </div>

{% endblock %}

Dar/customer/templates/my_ads.html
{% extends 'costumerBase.html' %}

{% block title %}آگهی‌های ثبت شده توسط من{% endblock %}
{% block bootstrap %}
<style>
    h3.h3{text-align:center;margin:1em;text-transform:capitalize;font-size:1.7em;}
    .demo{padding:45px 0}
.product-grid{font-family:Raleway,sans-serif;text-align:center;padding:0 0 72px;border:1px solid rgba(0,0,0,.1);overflow:hidden;position:relative;z-index:1}
.product-grid .product-image{position:relative;transition:all .3s ease 0s}
.product-grid .product-image a{display:block}
.product-grid .product-image img{width:100%;height:auto}
.product-grid .pic-1{opacity:1;transition:all .3s ease-out 0s}
.product-grid:hover .pic-1{opacity:1}
.product-grid .pic-2{opacity:0;position:absolute;top:0;left:0;transition:all .3s ease-out 0s}
.product-grid:hover .pic-2{opacity:1}
.product-grid .social{width:150px;padding:0;margin:0;list-style:none;opacity:0;transform:translateY(-50%) translateX(-50%);position:absolute;top:60%;left:50%;z-index:1;transition:all .3s ease 0s}
.product-grid:hover .social{opacity:1;top:50%}
.product-grid .social li{display:inline-block}
.product-grid .social li a{color:#fff;background-color:#333;font-size:16px;line-height:40px;text-align:center;height:40px;width:40px;margin:0 2px;display:block;position:relative;transition:all .3s ease-in-out}
.product-grid .social li a:hover{color:#fff;background-color:#ef5777}
.product-grid .social li a:after,.product-grid .social li a:before{content:attr(data-tip);color:#fff;background-color:#000;font-size:12px;letter-spacing:1px;line-height:20px;padding:1px 5px;white-space:nowrap;opacity:0;transform:translateX(-50%);position:absolute;left:50%;top:-30px}
.product-grid .social li a:after{content:'';height:15px;width:15px;border-radius:0;transform:translateX(-50%) rotate(45deg);top:-20px;z-index:-1}
.product-grid .social li a:hover:after,.product-grid .social li a:hover:before{opacity:1}
.product-grid .product-discount-label,.product-grid .product-new-label{color:#fff;background-color:#ef5777;font-size:12px;text-transform:uppercase;padding:2px 7px;display:block;position:absolute;top:10px;left:0}
.product-grid .product-discount-label{background-color:#333;left:auto;right:0}
.product-grid .rating{color:#FFD200;font-size:12px;padding:12px 0 0;margin:0;list-style:none;position:relative;z-index:-1}
.product-grid .rating li.disable{color:rgba(0,0,0,.2)}
.product-grid .product-content{background-color:#fff;text-align:center;padding:12px 0;margin:0 auto;position:absolute;left:0;right:0;bottom:-27px;z-index:1;transition:all .3s}
.product-grid:hover .product-content{bottom:0}
.product-grid .title{font-size:13px;font-weight:400;letter-spacing:.5px;text-transform:capitalize;margin:0 0 10px;transition:all .3s ease 0s}
.product-grid .title a{color:#828282}
.product-grid .title a:hover,.product-grid:hover .title a{color:#ef5777}
.product-grid .price{color:#333;font-size:17px;font-family:Montserrat,sans-serif;font-weight:700;letter-spacing:.6px;margin-bottom:8px;text-align:center;transition:all .3s}
.product-grid .price span{color:#999;font-size:13px;font-weight:400;text-decoration:line-through;margin-left:3px;display:inline-block}
.product-grid .add-to-cart{color:#000;font-size:13px;font-weight:600}
@media only screen and (max-width:990px){.product-grid{margin-bottom:30px}
}
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
{% endblock %}
{% block script %}
    function f(){alert("درخواست رزرو با موفقیت تایید گردید")}
    function g(){alert("درخواست رزرو با موفقیت رد گردید")}
    function printDiv(divName) {
    var printContents = document.getElementById(divName).innerHTML;
    var originalContents = document.body.innerHTML;

    document.body.innerHTML = printContents;

    window.print();

    document.body.innerHTML = originalContents;
    }
    function save(filename, divName) {
    var el = document.createElement('a');
    el.setAttribute('href', 'data:text/html;charset=utf-8,' +
    encodeURIComponent(document.getElementById(divName).innerHTML));
    el.setAttribute('download', filename);
    el.style.display = 'none';
    document.body.appendChild(el);
    el.click();
    document.body.removeChild(el);
    }
{% endblock %}

{% block content %}

<div class="main">



<div class="container">
    <h3 class="h3">shopping Demo-2 </h3>
    <div class="row">
        {% for ad in advertises %}
            <div class="col-md-3 col-sm-6">
            <div class="product-grid">
                <div class="product-image">
                    <a href="{% url 'customer:view_ad' ad.pk %}">
                        <img class="pic-1" src="{{ ad.image_advertise_set.all.0.image.url }}">
                        <img class="pic-2" src="{{ ad.image_advertise_set.all.0.image.url }}">
                    </a>
                    <ul class="social">
                        <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    </ul>
                    <span class="product-new-label">20%</span>
                </div>
                <ul class="rating">
                    <li class="fa fa-star"></li>
                    <li class="fa fa-star"></li>
                    <li class="fa fa-star"></li>
                    <li class="fa fa-star"></li>
                    <li class="fa fa-star disable"></li>
                </ul>
                <div class="product-content">
                    <h3 class="title">{{ ad.title }}</h3>
                    <div class="price">{{ ad.price }} Toman
                        <span>{{ ad.price }} Toman</span>
                    </div>
                    <a class="add-to-cart" href="{% url 'customer:view_ad' ad.pk %}">مشاهده</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

</div>

{% endblock %}

Dar/customer/templates/show_search_result.html
{% extends 'costumerBase.html' %}

{% block title %}
    نتایج جست و جو
{% endblock %}



{% block content %}


    <div id="printableArea">
    <table>
        <tr>
            <th>مشاهده</th>
            <th>وضعیت</th>
            <th>قیمت</th>
            <th>تاریخ ثبت</th>
            <th>عنوان</th>
            <th>شماره</th>
        </tr>
        {% for ad in ads %}
            <tr>
                <td><a href="{% url 'customer:view_ad' ad.pk %}" ><img src="../../../static/images/view.png" title="مشاهده" class="linkImg1"></a></td>
                <td>{{ ad.status }}</td>
                <td>{{ ad.price }}</td>
                <td>{{ ad.published_date|date:"Y / m / d" }}</td>
                <td>{{ ad.title }}</td>
                <td>
                    {{ forloop.counter }}
                </td>
            </tr>
        {% endfor %}




    </table>

{% endblock %}